version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: keycloak
    ports:
      - "3306:3306"
  keycloak:
    image: mihaibob/keycloak:15.0.1
    container_name: keycloak
    depends_on:
      - db
    command:
      [
          '-b',
          '0.0.0.0',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Djboss.socket.binding.port-offset=1000',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: 1
    ports:
      - "9080:9080"
      - "9443:9443"
      - "10990:10990"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"